# Generated by Django 4.1.13 on 2023-12-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
