# Generated by Django 4.1.13 on 2023-12-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
