# Generated by Django 4.1.13 on 2023-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
