# Generated by Django 4.1.13 on 2023-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='location',
        ),
    ]
