# Generated by Django 4.2.6 on 2023-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('updated_timestamp', models.TimeField()),
            ],
        ),
    ]
