# Generated by Django 4.2.5 on 2023-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('updated_timestamp', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
