# Generated by Django 4.1.13 on 2023-12-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('departmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=30)),
                ('dob', models.DateField(null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudop.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
